name: Test sh script
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - "main"
runs:
    steps:
        - name: Check sh script exits and fails job
          shell: bash
          run: sh scripts/test.sh
